/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Dao;
import model.Leitor;

/**
 *
 * @author Jefferson
 */
public class CadastroLeitor extends javax.swing.JFrame {

    /**
     * Creates new form LeitorCadastro
     */
    public CadastroLeitor() {
        initComponents();
        jLabel13.setVisible(false);
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeLeitor = new javax.swing.JTextField();
        txtCpfLeitor = new javax.swing.JTextField();
        txtEmailLeitor = new javax.swing.JTextField();
        txtTelefoneLeitor = new javax.swing.JTextField();
        txtEnderecoLeitor = new javax.swing.JTextField();
        txtBairroLeitor = new javax.swing.JTextField();
        txtNumeroLeitor = new javax.swing.JTextField();
        txtNascimentoLeitor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCidadeLeitor = new javax.swing.JTextField();
        txtCepLeitor = new javax.swing.JTextField();
        btEditarLeitor = new javax.swing.JButton();
        btExcluirLeitor = new javax.swing.JButton();
        btSalvarLeitor = new javax.swing.JButton();
        jcUfleitor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtComplementoLeitor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSenhaConfirmacao = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setTitle("Sistema de Gerenciamento de Biblioteca – SGB");
        setMinimumSize(new java.awt.Dimension(104, 36));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de leitor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel3.setText("Data de Nasc.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel6.setText("Telefone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel8.setText("Número");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel9.setText("Bairro");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));
        getContentPane().add(txtNomeLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 440, -1));
        getContentPane().add(txtCpfLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 132, -1));
        getContentPane().add(txtEmailLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 438, -1));
        getContentPane().add(txtTelefoneLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 175, -1));
        getContentPane().add(txtEnderecoLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 290, -1));
        getContentPane().add(txtBairroLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 132, -1));
        getContentPane().add(txtNumeroLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 132, -1));
        getContentPane().add(txtNascimentoLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 132, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setText("Cidade");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel11.setText("UF");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        jLabel12.setText("CEP");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));
        getContentPane().add(txtCidadeLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 238, -1));

        txtCepLeitor.setName(""); // NOI18N
        getContentPane().add(txtCepLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 132, -1));

        btEditarLeitor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEditarLeitor.setText("Editar");
        getContentPane().add(btEditarLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, -1));

        btExcluirLeitor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluirLeitor.setText("Excluir");
        btExcluirLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirLeitorActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, -1, -1));

        btSalvarLeitor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSalvarLeitor.setText("Salvar");
        btSalvarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarLeitorActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        jcUfleitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "PE", "RN", "PB", "PI", "CE", "BA", "MG" }));
        getContentPane().add(jcUfleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        jLabel13.setText("ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtId.setFocusCycleRoot(true);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 132, -1));

        jLabel14.setText("Complemento");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));
        getContentPane().add(txtComplementoLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 180, -1));

        jLabel15.setText("Senha");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 200, -1));

        jLabel16.setText("Nome do usuário (Login)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));
        getContentPane().add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 180, -1));

        txtSenhaConfirmacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenhaConfirmacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSenhaConfirmacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSenhaConfirmacaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSenhaConfirmacaoMousePressed(evt);
            }
        });
        txtSenhaConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfirmacaoActionPerformed(evt);
            }
        });
        txtSenhaConfirmacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSenhaConfirmacaoPropertyChange(evt);
            }
        });
        getContentPane().add(txtSenhaConfirmacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 200, -1));

        jLabel17.setText("Confirmar senha");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leitores2.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        setSize(new java.awt.Dimension(827, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarLeitorActionPerformed

        String senha = new String(txtSenha.getPassword());
        String senha2 = new String(txtSenhaConfirmacao.getPassword());

//        if ("".equals(txtId.getText())) {
//            JOptionPane.showMessageDialog(null, "Digite o ID válido para o leitor.","ATENÇÃO!" ,JOptionPane.ERROR_MESSAGE);
//
//        } else 
        if ("".equals(txtNomeLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o nome do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtNomeLeitor.requestFocus();

        } else if ("".equals(txtNascimentoLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data de nascimento do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtNascimentoLeitor.requestFocus();

        } else if ("".equals(txtCpfLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o CPF do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtCpfLeitor.requestFocus();

        } else if ("".equals(txtTelefoneLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o telefone do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtTelefoneLeitor.requestFocus();

        } else if ("".equals(txtEmailLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o e-mail do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtEmailLeitor.requestFocus();

        } else if ("".equals(txtEnderecoLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o endereço do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtEnderecoLeitor.requestFocus();

        } else if ("".equals(txtNumeroLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o numero do endereço do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtNumeroLeitor.requestFocus();

        } else if ("".equals(txtBairroLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o bairro do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtBairroLeitor.requestFocus();
        } else if ("".equals(txtCidadeLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a cidade do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtCidadeLeitor.requestFocus();
        } else if ("--".equals(jcUfleitor.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Selecione o estado do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("".equals(txtCepLeitor.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o CEP do leitor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtCepLeitor.requestFocus();
        } else if ("".equals(txtNomeUsuario.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o nome do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtNomeUsuario.requestFocus();
        } else if ("".equals(senha)) {
            JOptionPane.showMessageDialog(null, "Digite a senha.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();
        } else if ("".equals(senha2)) {
            JOptionPane.showMessageDialog(null, "Confirme a senha.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtSenhaConfirmacao.requestFocus();
        } else if (!senha.equals(senha2)) {
            JOptionPane.showMessageDialog(null, "As senhas não correspondem.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();

        } else {

            Leitor leitor = new Leitor();

            //leitor.setIdLeitor(Integer.parseInt(txtId.getText()));
            leitor.setNome(txtNomeLeitor.getText());
            leitor.setDataNascimento(txtNascimentoLeitor.getText());
            leitor.setCpf(txtCpfLeitor.getText());
            leitor.setTelefone(txtTelefoneLeitor.getText());
            leitor.setEmail(txtEmailLeitor.getText());
            leitor.setEndereco(txtEnderecoLeitor.getText());
            leitor.setNumero(txtNumeroLeitor.getText());
            leitor.setComplemento(txtComplementoLeitor.getText());
            leitor.setBairro(txtBairroLeitor.getText());
            leitor.setCidade(txtCidadeLeitor.getText());
//        leitor.setUf(jcUfleitor.getItemAt(WIDTH));
            leitor.setUf(jcUfleitor.getSelectedItem().toString());
            leitor.setCep(txtCepLeitor.getText());
            leitor.setUsuario(txtNomeUsuario.getText());
            leitor.setSenha(String.valueOf(txtSenha.getPassword()));

            Dao dao = new Dao();

            int resp;
            boolean status;
            String nomeLeitor;

            status = dao.conectar();
            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.");

            } else {
                resp = dao.salvarLeitor(leitor);

                if (resp == 1) {
                    JOptionPane.showMessageDialog(null, " Leitor cadastrado com sucesso!");
                    limparCampos();

                } else if (resp == 1062) {
                    JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                    //txtId.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados.");

                }
                dao.desconectar();
            }
        }

    }//GEN-LAST:event_btSalvarLeitorActionPerformed

    private void txtSenhaConfirmacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoMouseClicked

    }//GEN-LAST:event_txtSenhaConfirmacaoMouseClicked

    private void txtSenhaConfirmacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoMouseEntered

    }//GEN-LAST:event_txtSenhaConfirmacaoMouseEntered

    private void txtSenhaConfirmacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoMouseExited

    }//GEN-LAST:event_txtSenhaConfirmacaoMouseExited

    private void txtSenhaConfirmacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoMousePressed

    }//GEN-LAST:event_txtSenhaConfirmacaoMousePressed

    private void txtSenhaConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoActionPerformed

    }//GEN-LAST:event_txtSenhaConfirmacaoActionPerformed

    private void txtSenhaConfirmacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSenhaConfirmacaoPropertyChange

    }//GEN-LAST:event_txtSenhaConfirmacaoPropertyChange

    private void btExcluirLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirLeitorActionPerformed

    }//GEN-LAST:event_btExcluirLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLeitor().setVisible(true);
            }
        });
    }

    void limparCampos() {
        txtId.setText(null);
        txtNomeLeitor.setText(null);
        txtNascimentoLeitor.setText(null);
        txtCpfLeitor.setText(null);
        txtTelefoneLeitor.setText(null);
        txtEmailLeitor.setText(null);
        txtEnderecoLeitor.setText(null);
        txtNumeroLeitor.setText(null);
        txtComplementoLeitor.setText(null);
        txtBairroLeitor.setText(null);
        txtCidadeLeitor.setText(null);
        jcUfleitor.setSelectedItem("--");
        txtCepLeitor.setText(null);
        txtNomeUsuario.setText(null);
        txtSenha.setText(null);
        txtSenhaConfirmacao.setText(null);
        txtNomeLeitor.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarLeitor;
    private javax.swing.JButton btExcluirLeitor;
    private javax.swing.JButton btSalvarLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcUfleitor;
    private javax.swing.JTextField txtBairroLeitor;
    private javax.swing.JTextField txtCepLeitor;
    private javax.swing.JTextField txtCidadeLeitor;
    private javax.swing.JTextField txtComplementoLeitor;
    private javax.swing.JTextField txtCpfLeitor;
    private javax.swing.JTextField txtEmailLeitor;
    private javax.swing.JTextField txtEnderecoLeitor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNascimentoLeitor;
    private javax.swing.JTextField txtNomeLeitor;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtNumeroLeitor;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaConfirmacao;
    private javax.swing.JTextField txtTelefoneLeitor;
    // End of variables declaration//GEN-END:variables
}
