/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.ConexaoDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Jefferson
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        usuarioLogado();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }
    
public void usuarioLogado(){ // CONEXÃO COM O BANDO DE DADOS PARA PEGAR NA TABELA LOG O ULTIMO USUARIO LOGADO E MOSTRAR NA TELA
    
      ConexaoDAO conexao = new ConexaoDAO();
        Connection conn =  conexao.conectarlog();

        try {
//            String consulta = "SELECT * FROM pessoa WHERE nome like 'J%'";
            String consulta = "SELECT usuario FROM log ORDER BY id DESC LIMIT 1;";
            Statement stm = conn.createStatement();
            ResultSet resultado = stm.executeQuery(consulta);

            while (resultado.next()) {

//                NewJFrame tela = new NewJFrame();
                String nome = resultado.getString("USUARIO");
                
                String primeiraLetra = nome.substring(0,1).toUpperCase();// a primeira letra do nome digitado fica maiuscula
                String restoDoTexto = nome.substring(1).toLowerCase();// da sgunda letra em diante do nome digitado fica miniscula

                txtUsuarioLogado.setText(primeiraLetra + restoDoTexto);

            }

        } catch (Exception ex) {
            System.out.println("Nao conseguiu consultar os dados de Log");
        } finally {
            conexao.desconectarLog(conn);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btEditora = new javax.swing.JButton();
        btAutores = new javax.swing.JButton();
        btLeitores = new javax.swing.JButton();
        btLivros = new javax.swing.JButton();
        btUsuarios = new javax.swing.JButton();
        txtUsuarioLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btEmprestimo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btCobsultaLivro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btRelatorioLivro = new javax.swing.JButton();
        btRelatorioEmprestimo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Biblioteca – SGB");

        btEditora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editora3.png"))); // NOI18N
        btEditora.setText("Editoras");
        btEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditoraActionPerformed(evt);
            }
        });

        btAutores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Autor.png"))); // NOI18N
        btAutores.setText("Autores");
        btAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutoresActionPerformed(evt);
            }
        });

        btLeitores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLeitores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leitores2.png"))); // NOI18N
        btLeitores.setText("Leitores");
        btLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLeitoresActionPerformed(evt);
            }
        });

        btLivros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/livros.png"))); // NOI18N
        btLivros.setText("Livros");
        btLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivrosActionPerformed(evt);
            }
        });

        btUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add usuario.png"))); // NOI18N
        btUsuarios.setText("Usuários");
        btUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuariosActionPerformed(evt);
            }
        });

        txtUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuarioLogado.setText("usuario.logado");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Usuario logado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioLogado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEditora)
                        .addGap(18, 18, 18)
                        .addComponent(btAutores)
                        .addGap(18, 18, 18)
                        .addComponent(btLeitores)
                        .addGap(18, 18, 18)
                        .addComponent(btLivros)
                        .addGap(18, 18, 18)
                        .addComponent(btUsuarios)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuarioLogado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditora)
                    .addComponent(btAutores)
                    .addComponent(btLeitores)
                    .addComponent(btLivros)
                    .addComponent(btUsuarios))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        btEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emprestimo.png"))); // NOI18N
        btEmprestimo.setText("Empréstimo");
        btEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btEmprestimo)
                .addContainerGap(1122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btEmprestimo)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empréstimo", jPanel2);

        btCobsultaLivro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCobsultaLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/consulta.png"))); // NOI18N
        btCobsultaLivro.setText("Livros/Títulos");
        btCobsultaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCobsultaLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btCobsultaLivro)
                .addContainerGap(1207, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btCobsultaLivro)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", jPanel3);

        btRelatorioLivro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRelatorioLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analise-de-dados.png"))); // NOI18N
        btRelatorioLivro.setText("Livros Cadastrados");

        btRelatorioEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRelatorioEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analise-de-dados.png"))); // NOI18N
        btRelatorioEmprestimo.setText("Livros Emprestados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btRelatorioLivro)
                .addGap(73, 73, 73)
                .addComponent(btRelatorioEmprestimo)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRelatorioEmprestimo)
                    .addComponent(btRelatorioLivro))
                .addGap(378, 378, 378))
        );

        jTabbedPane1.addTab("Relatórios", jPanel4);

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btSair)
                .addContainerGap(1219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btSair)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sair", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1550, 762);
    }// </editor-fold>//GEN-END:initComponents

    private void btAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutoresActionPerformed
        CadastroAutor autor = new CadastroAutor();
        autor.setVisible(true);
    }//GEN-LAST:event_btAutoresActionPerformed

    private void btLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLeitoresActionPerformed
        CadastroLeitor leitorCadastro = new CadastroLeitor();
        leitorCadastro.setVisible(true);
    }//GEN-LAST:event_btLeitoresActionPerformed

    private void btLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivrosActionPerformed
        CadastroLivro cadastroLivro = new CadastroLivro();
        cadastroLivro.setVisible(true);
    }//GEN-LAST:event_btLivrosActionPerformed

    private void btUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuariosActionPerformed
        CadastroUsuario cadastroUsuario = new CadastroUsuario();
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_btUsuariosActionPerformed

    private void btEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditoraActionPerformed
       CadastroEditora editora = new CadastroEditora();
       editora.setVisible(true);
    }//GEN-LAST:event_btEditoraActionPerformed

    private void btEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestimoActionPerformed
       CadastroEmprestimo emprestimo = new CadastroEmprestimo();
       emprestimo.setVisible(true);
    }//GEN-LAST:event_btEmprestimoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
       Login login = new Login();

        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCobsultaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCobsultaLivroActionPerformed
        ConsultaLivro consultaLivro = new ConsultaLivro();
        consultaLivro.setVisible(true);
    }//GEN-LAST:event_btCobsultaLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAutores;
    private javax.swing.JButton btCobsultaLivro;
    private javax.swing.JButton btEditora;
    private javax.swing.JButton btEmprestimo;
    private javax.swing.JButton btLeitores;
    private javax.swing.JButton btLivros;
    private javax.swing.JButton btRelatorioEmprestimo;
    private javax.swing.JButton btRelatorioLivro;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btUsuarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
