package view;

import connection.TabelaAutorDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Autor;
import model.Dao;
import model.TabelaAutor;

/**
 *
 * @author Jefferson
 */
public class CadastroAutor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAutor
     */
    public CadastroAutor() {
        setTitle("Sistema de Gerenciamento de Biblioteca – SGB - Cadastro de Autor");
        initComponents();
        setResizable(false);

        DefaultTableModel modelo = (DefaultTableModel) tabelaAutor.getModel();
        tabelaAutor.setRowSorter(new TableRowSorter(modelo));
        readTabela();

    }

    public void readTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaAutor.getModel();
        modelo.setNumRows(0);
        TabelaAutorDAO pdao = new TabelaAutorDAO();

        for (TabelaAutor autor : pdao.read()) {
            modelo.addRow(new Object[]{
                autor.getId(),
                autor.getNome()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAutor = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setResizable(false);

        jLabel1.setText("Nome do Autor");

        txtAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        tabelaAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Autor"
            }
        ));
        tabelaAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAutor);
        if (tabelaAutor.getColumnModel().getColumnCount() > 0) {
            tabelaAutor.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaAutor.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEditar.setText("Atualizar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Cadastro de Autor");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Autor.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btEditar)
                                .addGap(43, 43, 43)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(785, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if ("".equals(txtAutor.getText())) {// SE O CAMPO txtautor FOR VAZIO, ABRIRÁ UMA CAIXA DE MENSAGEM SOLICITANDO QUE ESCRE O NOME.
            JOptionPane.showMessageDialog(null, "Digite o nome do Autor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else {//SE FOR ESCRITO ALGO NO CAMPO TEXTO, SERÁ EXECUTADO O CÓDIGO ABAIXO

            Autor autor = new Autor(txtAutor.getText());

            Dao dao = new Dao();

            int resp;
            boolean status;

            status = dao.conectar();
            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar com o servidor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            } else {
                resp = dao.salvarAutor(autor);
                if (resp == 1) {
                    JOptionPane.showMessageDialog(null, "Autor cadastrado com sucesso!");

//                    DefaultTableModel tbprodutos = (DefaultTableModel) tabelaAutor.getModel();
//                    Object[] dados = {txtAutor.getText()};
//                    tbprodutos.addRow(dados);
                    readTabela();

                    txtAutor.setText(null);//APÓS CLICAR EM OK, O TEXTO É APAGADO
                    txtAutor.requestFocus();// APÓS CLICAR EM OK, O CURSOR SERÁ APONTADO PARA O CAMPO DE TEXTO txt.autor

                } else if (resp == 1062) {
                    JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                    txtAutor.requestFocus();//APÓS CLICAR EM OK, O CURSOR SERÁ APONTADO PARA O CAMPO DE TEXTO txt.autor

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados.");

                }

                dao.desconectar();
            }

        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        if (tabelaAutor.getSelectedRow() != -1) {

            // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
            TabelaAutor a = new TabelaAutor(); // estancia a tabelaAutor

            TabelaAutorDAO dao = new TabelaAutorDAO(); //estancia a tabelaAutorDAO

            a.setNome(txtAutor.getText()); // capta os dados do campo de texto txtAutor e seta no atributo nome

            a.setId((int) tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 0));// capta o ID selecionado e seta no atributo ID
            dao.update(a); // chama o metodo UPDATE

            txtAutor.setText(null);// limpa o campo de texto
            readTabela(); // atualiza a tabela

        }

    }//GEN-LAST:event_btEditarActionPerformed

    private void tabelaAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAutorMouseClicked

        if (tabelaAutor.getSelectedRow() != -1) {

            // txtIDold.setText(tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 0).toString());
            txtAutor.setText(tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 1).toString());

//            txtID.setText(tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 1).toString());
//            txtAutor.setText(tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 2).toString());
//            txtAutor.setText(tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tabelaAutorMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir " + txtAutor.getText()+ "?" , "Confirmação",JOptionPane.YES_NO_OPTION);
       
        if (resposta == JOptionPane.YES_OPTION) {

            if (tabelaAutor.getSelectedRow() != -1) {

                // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
                TabelaAutor a = new TabelaAutor(); // estancia a tabelaAutor

                TabelaAutorDAO dao = new TabelaAutorDAO(); //estancia a tabelaAutorDAO

                a.setNome(txtAutor.getText()); // capta os dados do campo de texto txtAutor e seta no atributo nome

                a.setId((int) tabelaAutor.getValueAt(tabelaAutor.getSelectedRow(), 0));// capta o ID selecionado e seta no atributo ID
                dao.delete(a); // chama o metodo UPDATE

                txtAutor.setText(null);// limpa o campo de texto
                readTabela(); // atualiza a tabela

            }
        }else{
            
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAutor;
    private javax.swing.JTextField txtAutor;
    // End of variables declaration//GEN-END:variables
}
