package view;

import connection.TabelaUsuarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Dao;
import model.TabelaAutor;
import model.Usuario;

public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        setTitle("Sistema de Gerenciamento de Biblioteca – SGB - Cadastro de Usuário");
        setResizable(false);
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) tabelaCadastroUsuario.getModel();
        tabelaCadastroUsuario.setRowSorter(new TableRowSorter(modelo));
        readTabela();

        txtId.setVisible(false);
        jLabel6.setVisible(false);
    }

    public void readTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaCadastroUsuario.getModel();
        modelo.setNumRows(0);
        TabelaUsuarioDAO edao = new TabelaUsuarioDAO();

        for (Usuario usuario : edao.read()) { //referencia a classe
            modelo.addRow(new Object[]{
                usuario.getIdUsuario(),
                usuario.getNome(),
                usuario.getNomeUsuario(), //usuario.getSenha(),
            // usuario.getNivelHierarquico()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jcNivelHierarquico = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtSenha2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCadastroUsuario = new javax.swing.JTable();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        jLabel1.setText("Usuário");

        jLabel2.setText("Confirmar senha");

        jLabel3.setText("Nível Hierárquico");

        jcNivelHierarquico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Administrador", "Atendente", "Gerente" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Cadastro de Usuário");

        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtSenha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenha2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSenha2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSenha2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSenha2MousePressed(evt);
            }
        });
        txtSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha2ActionPerformed(evt);
            }
        });
        txtSenha2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSenha2PropertyChange(evt);
            }
        });

        jLabel5.setText("Senha");

        jLabel6.setText("ID");

        jLabel7.setText("Nome");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add usuario.png"))); // NOI18N

        tabelaCadastroUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Nome Usuário"
            }
        ));
        tabelaCadastroUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCadastroUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCadastroUsuario);
        if (tabelaCadastroUsuario.getColumnModel().getColumnCount() > 0) {
            tabelaCadastroUsuario.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaCadastroUsuario.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaCadastroUsuario.getColumnModel().getColumn(1).setMinWidth(500);
            tabelaCadastroUsuario.getColumnModel().getColumn(1).setMaxWidth(800);
        }

        btAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSenha2)
                                            .addComponent(txtUsuario)
                                            .addComponent(txtSenha)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcNivelHierarquico, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAtualizar)
                .addGap(18, 18, 18)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcNivelHierarquico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btAtualizar)
                    .addComponent(btExcluir)
                    .addComponent(btLimpar))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(835, 792));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String senha = new String(txtSenha.getPassword());
        String senha2 = new String(txtSenha2.getPassword());

//        if ("".equals(txtId.getText())) {
//            JOptionPane.showMessageDialog(null, "Digite o ID do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
//
//        } else 
        if ("".equals(txtUsuario.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o nome do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("".equals(senha)) {
            JOptionPane.showMessageDialog(null, "Digite a senha do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("".equals(senha2)) {
            JOptionPane.showMessageDialog(null, "Confirme a senha do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("Selecionar".equals(jcNivelHierarquico.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Escolha o nível Hierárquico do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if (!senha.equals(senha2)) {
            JOptionPane.showMessageDialog(null, "As senhas não correspondem.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();

        } else {

            Usuario usuario = new Usuario();

            // usuario.setIdUsuario(Integer.parseInt(txtId.getText()));
            usuario.setNome(txtNome.getText());
            usuario.setNomeUsuario(txtUsuario.getText());
            usuario.setSenha(String.valueOf(txtSenha.getPassword()));
//            usuario.setNivelHierarquico(jcNivelHierarquico.getItemAt(WIDTH));
            usuario.setNivelHierarquico(jcNivelHierarquico.getSelectedItem().toString());

            Dao dao = new Dao();

            int resp;
            boolean status;

            status = dao.conectar();
            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.");
            } else {
                resp = dao.salvarUsuario(usuario);
                if (resp == 1) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                    readTabela();
//                    JOptionPane.showMessageDialog(null,usuario.getNivelHierarquico());
                    limparCampo();
                } else if (resp == 1062) {
                    JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                    txtId.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados.");
                }
                dao.desconectar();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSenha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha2MouseClicked


    }//GEN-LAST:event_txtSenha2MouseClicked

    private void txtSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha2ActionPerformed

    }//GEN-LAST:event_txtSenha2ActionPerformed

    private void txtSenha2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha2MouseEntered

    }//GEN-LAST:event_txtSenha2MouseEntered

    private void txtSenha2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha2MouseExited

    }//GEN-LAST:event_txtSenha2MouseExited

    private void txtSenha2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSenha2PropertyChange

    }//GEN-LAST:event_txtSenha2PropertyChange

    private void txtSenha2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha2MousePressed

    }//GEN-LAST:event_txtSenha2MousePressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o usuário(a) " + txtUsuario.getText() + "?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            if (tabelaCadastroUsuario.getSelectedRow() != -1) {

                // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
                Usuario usuario = new Usuario(); // estancia a tabelaAutor

                TabelaUsuarioDAO dao = new TabelaUsuarioDAO(); //estancia a tabelaAutorDAO

                usuario.setNome(txtNome.getText()); // capta os dados do campo de texto txtAutor e seta no atributo nome

                usuario.setIdUsuario((int) tabelaCadastroUsuario.getValueAt(tabelaCadastroUsuario.getSelectedRow(), 0));// capta o ID selecionado e seta no atributo ID

                dao.delete(usuario); // chama o metodo UPDATE

                txtNome.setText(null);// limpa o campo de texto
                txtUsuario.setText(null);// limpa o campo de texto
                txtSenha.setText(null);// limpa o campo de texto
                txtSenha2.setText(null);// limpa o campo de texto
                readTabela(); // atualiza a tabela

            }
        } else {

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tabelaCadastroUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCadastroUsuarioMouseClicked

        if (tabelaCadastroUsuario.getSelectedRow() != -1) {

            //  txtId.setText(tabelaCadastroUsuario.getValueAt(tabelaCadastroUsuario.getSelectedRow(), 0).toString());
            txtNome.setText(tabelaCadastroUsuario.getValueAt(tabelaCadastroUsuario.getSelectedRow(), 1).toString());
            txtUsuario.setText(tabelaCadastroUsuario.getValueAt(tabelaCadastroUsuario.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_tabelaCadastroUsuarioMouseClicked

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed

        String senha = new String(txtSenha.getPassword());
        String senha2 = new String(txtSenha2.getPassword());

//        if ("".equals(txtId.getText())) {
//            JOptionPane.showMessageDialog(null, "Digite o ID do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
//
//        } else 
        if ("".equals(txtUsuario.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o nome do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("".equals(senha)) {
            JOptionPane.showMessageDialog(null, "Digite a senha do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("".equals(senha2)) {
            JOptionPane.showMessageDialog(null, "Confirme a senha do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if ("Selecionar".equals(jcNivelHierarquico.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Escolha o nível Hierárquico do usuário.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else if (!senha.equals(senha2)) {
            JOptionPane.showMessageDialog(null, "As senhas não correspondem.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();

        } else {

            if (tabelaCadastroUsuario.getSelectedRow() != -1) {

                // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
                Usuario u = new Usuario(); // estancia a tabelaAutor

                TabelaUsuarioDAO dao = new TabelaUsuarioDAO(); //estancia a tabelaAutorDAO

                u.setIdUsuario((int) tabelaCadastroUsuario.getValueAt(tabelaCadastroUsuario.getSelectedRow(), 0));// capta o ID selecionado e seta no atributo ID
                u.setNome(txtNome.getText()); // capta os dados do campo de texto txtNome e ceta no atributo nome
                u.setNomeUsuario(txtUsuario.getText());//capta os dados do campo de texto txtUsuario e ceta no atributo nomeUsuario
                u.setNivelHierarquico(String.valueOf(jcNivelHierarquico.getSelectedItem())); //capta a opção selecionada e ceta no atributo NivelHierarquivo
                u.setSenha(String.valueOf(txtSenha.getPassword()));//capta os dados do campo de texto txtUsuario e ceta no atributo nomeUsuario

                dao.update(u); // chama o metodo UPDATE

                limparCampo();
                readTabela(); // atualiza a tabela

            }

        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampo();
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    public void limparCampo() {
        //txtId.setText(null);
        txtNome.setText(null);
        txtUsuario.setText(null);
        txtSenha.setText(null);
        txtSenha2.setText(null);
        jcNivelHierarquico.setSelectedItem("Selecionar");
        txtNome.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcNivelHierarquico;
    private javax.swing.JTable tabelaCadastroUsuario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
