
package view;


import connection.TabelaEditoraDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Dao;
import model.Editora;

import model.TabelaEditora;

public class CadastroEditora extends javax.swing.JFrame {

    public CadastroEditora() {
                setTitle("Sistema de Gerenciamento de Biblioteca – SGB - Cadastro de Editora");
        setResizable(false);
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) tabelaEditora.getModel();
        tabelaEditora.setRowSorter(new TableRowSorter(modelo));
        readTabela();
    }

    public void readTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaEditora.getModel();
        modelo.setNumRows(0);
        TabelaEditoraDAO pdao = new TabelaEditoraDAO();

        for (TabelaEditora editora : pdao.read()) {// referencia a classe
            modelo.addRow(new Object[]{
                editora.getId(),
                editora.getNomeEditora()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEditora = new javax.swing.JTable();
        bteditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel1.setText("Editora");

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tabelaEditora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Editora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEditora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEditoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEditora);
        if (tabelaEditora.getColumnModel().getColumnCount() > 0) {
            tabelaEditora.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaEditora.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        bteditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bteditar.setText("Atualizar");
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Cadastro de Editora");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editora3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtEditora)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(bteditar)
                                .addGap(55, 55, 55)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(757, 775));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if ("".equals(txtEditora.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o nome da Editora.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

        } else {

            Editora editora = new Editora(txtEditora.getText());

            Dao dao = new Dao();

            int resp;
            boolean status;

            status = dao.conectar();
            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar com o servidor.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

            } else {
                resp = dao.salvarEditora(editora);
                if (resp == 1) {
                    JOptionPane.showMessageDialog(null, "Editora cadastrada com sucesso!");
                    readTabela();
                    txtEditora.setText(null);//Apagar o campo de texto após salvar no Banco de dados.
                    txtEditora.requestFocus();

                } else if (resp == 1062) {
                    JOptionPane.showMessageDialog(null, "Matricula já cadastrada.", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados.");
                }
                dao.desconectar();
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tabelaEditoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEditoraMouseClicked
        if (tabelaEditora.getSelectedRow() != -1) {

            //txtID.setText(tabelaEditora.getValueAt(tabelaEditora.getSelectedRow(), 0).toString());
            txtEditora.setText(tabelaEditora.getValueAt(tabelaEditora.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_tabelaEditoraMouseClicked

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        
        if (tabelaEditora.getSelectedRow() != -1) {

            // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
            TabelaEditora e = new TabelaEditora(); // estancia a tabelaEditora

            TabelaEditoraDAO dao = new TabelaEditoraDAO(); //estancia a tabelaEditoraDAO

            e.setNomeEditora(txtEditora.getText()); // capta os dados do campo de texto txtEditora e seta no atributo nome
            e.setId((int)tabelaEditora.getValueAt(tabelaEditora.getSelectedRow(),0));// capta o ID selecionado e seta no atributo ID
            
            dao.update(e); // chama o metodo UPDATE
            txtEditora.setText(null);// limpa o campo de texto
            readTabela(); // atualiza a tabela

        }
    }//GEN-LAST:event_bteditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir " + txtEditora.getText()+ "?" , "Confirmação",JOptionPane.YES_NO_OPTION);
       
        if (resposta == JOptionPane.YES_OPTION) {

            if (tabelaEditora.getSelectedRow() != -1) {

                // tabelaAutor.setValueAt(txtAutor.getText(),tabelaAutor.getSelectedRow(),1);
                TabelaEditora e = new TabelaEditora(); // estancia a tabelEditora

                TabelaEditoraDAO dao = new TabelaEditoraDAO(); //estancia a tabelaEditora
                

                e.setNomeEditora(txtEditora.getText()); // capta os dados do campo de texto txtNomeEditora e seta no atributo nome

                e.setId((int) tabelaEditora.getValueAt(tabelaEditora.getSelectedRow(), 0));// capta o ID selecionado e seta no atributo ID
                dao.delete(e); // chama o metodo delete

                txtEditora.setText(null);// limpa o campo de texto
                readTabela(); // atualiza a tabela

            }
        }else{
            
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEditora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton bteditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEditora;
    private javax.swing.JTextField txtEditora;
    // End of variables declaration//GEN-END:variables
}
